env:
 - ZMQ="git://github.com/zeromq/zeromq3-x.git -b v3.2.2"
before_install:
 - sudo apt-get install uuid-dev
 - git clone --depth 1 $ZMQ zmqlib
 - cd zmqlib
 - ./autogen.sh
 - ./configure
 - make
 - sudo make install
 - sudo /sbin/ldconfig
 - cd ..
 - sudo npm install -g grunt-cli
 - npm install
language: node_js
node_js:
 - "0.8"
 - "0.10"
script: "grunt travis"
